### PR TITLE
Correct param name for Thriftpy TSSLSocket for Python 3

### PR DESCRIPTION
**Pull request by bquinart**
Proposed fix for #195

### CODE REVIEW

**Comment by wesm** [comment]
Looks OK to me. You tested this out and it works okay?

**Comment by bquinart** [comment]
Yes, tested on my Windows laptop with Python 3.

**Comment by wesm** [comment]
Merged. I will look to do some more testing when I can before releasing this fix, but you can pull from master for now

**Comment by wesm** [comment]
Thank you for the patience with these issues

**Pull request merged**
