### PR TITLE
Flatten module structure and combine dbapi/rpc code for beeswax and HS2

### PR DESCRIPTION
**Pull request by wesm**
I combined all the HS2 and beeswax code into their own standalone modules. More refactoring can happen later. I created a `dbapi.py` module so the refactor should not cause breakage unless people were importing from inside the `dbapi` submodule before

### CODE REVIEW

**Comment by wesm** [comment]
@laserson jenkins is green; feel free to merge if you are OK with the refactor

**Comment by laserson** [comment]
Manually merged in ee3c006

**Comment by wesm** [comment]
thanks!

**Comment by laserson** [comment]
Thanks *you*! :)

**Pull request closed without merging**
