### PR TITLE
Change async to run_async to support Python 3.7

### LINKED ISSUE #312: impyla does not support Python 3.7
Python 3.7 introduced a change which made `async` a reserved keyword

```
>>> from impala.dbapi import connect
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "../.venv/lib/python3.7/site-packages/impala/dbapi.py", line 28, in <module>
    import impala.hiveserver2 as hs2
  File "../.venv/lib/python3.7/site-packages/impala/hiveserver2.py", line 340
    async=True)
        ^
SyntaxError: invalid syntax
```

```
Python 3.7.0
impyla==0.14.1
```

### PR DESCRIPTION
**Pull request by cpcloud**
Closes #312

### CODE REVIEW

**Comment by cpcloud** [comment]
@gregrahn Can you review this patch? All tests run and pass for me locally except for these 3:

```
impala/tests/test_dbapi_connect.py::ImpalaConnectionTests::test_hive_nosasl_connect SKIPPED
impala/tests/test_dbapi_connect.py::ImpalaConnectionTests::test_hive_plain_connect FAILED
impala/tests/test_dbapi_connect.py::ImpalaConnectionTests::test_impala_plain_connect SKIPPED
```

I currently only have a NOSASL impala docker image set up (no hive image or installation). How are patches to this project usually verified?

**Comment by gregrahn** [comment]
@dknupp - Is this something that you might have time to look at?

**Comment by dknupp** [comment]
Can you add a description that references the issue being resolved?
https://github.com/cloudera/impyla/issues/312

As for the change itself, it looks pretty straightforward, but can you also squash the commits when you update the description?

**Comment by cpcloud** [comment]
I will have some time later today to close our this PR.

**Comment by xmnlab** [comment]
@cpcloud great. let me know if I can help in any way.

**Comment by cpcloud** [comment]
@dknupp Can you cut a release to PyPI? I can help with updating the conda-forge-feedstock

**Comment by jdemonasterio** [comment]
Really looking forward to this release :pray: Thanks!

**Comment by dknupp** [comment]
0.14.2 has been pushed to PyPI.

**Comment by joolius** [comment]
Still doesn't work. Installed impyla v 0.14.2.2 and getting this error

```
File "C:\Users\usr\AppData\Local\Continuum\anaconda3\lib\site-packages\impala\hiveserver2.py", line 340
    async=True)
        ^
SyntaxError: invalid syntax
```

**Comment by dknupp** [comment]
Sadly, this is expected. 0.14.2.2 is essentially just a repackaging of what was there before. When 0.14.2 was released, a few serious build breakages were discovered. We needed to roll back, but still increment the version number so that `pip install impyla` and `pip install -U impyla` still worked.

I was essentially following the recommendation of Doug Hellman in this blog post:
https://doughellmann.com/blog/2016/02/25/so-youve-released-a-broken-package-to-pypi-what-do-you-do-now/

I have a local tested patch for one of the newly discovered issues. I'll try to open a pull request for that today or tomorrow. Plan to look at the other next week.

Sorry for all the confusion.

**Comment by siddharthsudheer** [comment]
@dknupp has this been fixed yet? Thanks!

**Comment by dknupp** [comment]
@siddharthsudheer -- alpha release 0.15a1 is now up on pypi for you to try out.
`pip install impyla==0.15a1`

**Comment by siddharthsudheer** [comment]
@dknupp Thanks, will try it out!

**Pull request merged**
