### PR TITLE
Autoclose HiveServer2 connections

### PR DESCRIPTION
**Pull request by Saluev**
Now connections are closed on delete.

### CODE REVIEW

**Comment by wesm** [comment]
Is `close()` idempotent? What if it has been explicitly closed by the user?

**Comment by Saluev** [comment]
@wesm Yes, I've tested that scenario. My HiveServer2 connections were closing without errors for multiple times in a row.

**Comment by wesm** [comment]
thanks!

**Comment by Saluev** [comment]
By the way, I've figured out that `connection.close()` doesn't actually close anything. Cursors and queries continue to execute successfully after that.

**Pull request merged**
