### PR TITLE
Passing username for impersonation

### PR DESCRIPTION
**Pull request by gbrian**

### CODE REVIEW

**Comment by timarmstrong** [comment]
Can you add a test for this feature? Maybe you can use the effective_user() builtin function to make sure that it had the intended effect.

**Comment by gbrian** [comment]
Do you mean kind of:

```
def test_sqlalchemy_impersonation():
    engine = create_engine('impala://localhost')
    result = connection.execute("select effective_user() as effective_user")
    observed = result[0]['effective_user']
    expected = '?????'
    assert expected == observed

    impersonate = 'user1'
    engine = create_engine('impala://%s@localhost' % impersonate)
    result = connection.execute("select effective_user() as effective_user")
    observed = result[0]['effective_user']
    expected = impersonate
    assert expected == observed
```

**Comment by timarmstrong** [comment]
Something along those lines, yeah. I think the second part of that test is the most important. Mainly to prove that the 'effective_user' value gets plumbed all the way through to Impala correctly.

**Comment by huw0** [comment]
cloudera/impyla#281 indicates that impersonation works on a per-cursor basis.

Therefore can this PR be closed? I think it will be confusing to support impersonation in multiple places and this could lead to security issues where connections are re-used.

**Comment by gbrian** [comment]
Not needed

**Pull request closed without merging**
